# Generated by Django 4.0.2 on 2022-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('is_true', models.BooleanField()),
            ],
        ),
    ]
